language: node_js
# node版本 node -v
node_js: "16.14.2"
#缓存依赖
cache:
  directories:
    - node_modules
before_install:
  - echo "start install"       
install:
  - yarn
before_script:
  - git config user.name "${UserName}"
  - git config user.email "${UserEmail}"
  - git remote rm origin
  - git remote add origin https://${UserName}:${GithubToken}@github.com/${RepName}
  - git remote -v
script: yarn deploy
# 只有指定的分支提交时才会运行脚本
branches:
  only:
    - main