name: Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' 
      - name: Setup git      
        run: |
          git config user.name "${{ secrets.USER_NAME }}"
          git config user.email "${{ secrets.USER_EMAIL }}"
          git remote rm origin
          git remote add origin https://${{ secrets.USER_NAME }}:${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/${{ secrets.REP_NAME }}
          git remote -v 
      - name: Init project
        run: yarn
      - name: Build and tests
        run: yarn deploy